### ISSUE TITLE
Write up is missing information

### ISSUE THREAD

**Issue by djdembeck** [foureight84/traefik-pihole-doh#1]
I am trying to follow your write up. There are a few issues I've encountered:
- the compose file uses `traefik.yaml` but this is not mentioned in the guide. I had to create the file or comment it out of the compose file for traefik to start up.
- `agent_network` is required but not mentioned in the write up.
- I'm assuming this is in the missing `traefik.yaml`, but there is no entrypoints setup in the traefik portion of the compose yaml's.

I've been unable to get this working, and figured I would point out some of the issues I've encountered.

**Comment by foureight84** [comment]
Hey, it has been a while since I've updated this repo. Thanks for bringing this up. I've made changes to the `docker-compose.yaml` in the `mgmt` stack to reflect changes for portainer and traefik since the last commit.

- `traefik.yaml` is a configuration file. You can either use this method or declare it inline (cli and in the docker-compose file). I made this split since it makes more sense to leave it out of the compose file. You can read more about this via Traefik's documentation: https://doc.traefik.io/traefik/providers/docker/#configuration-examples. A good reason to do this is to keep the docker-compose.yaml clean. Once you start adding middlewares, redirect, and other features to traefik, it will get messy if they were declared in the cli/compose file.
- `agent_network` was not referenced in the write-up but just needed to be created like you had to create the traefik overlay network from the write-up. I can't remember why I added this after the fact but it's been removed since Portainer has had some changes over the year as well. 
- traefik's port has also changed for the webui access from 8080 to 80, the loadbalance label entry has been updated. Entrypoints ports and reference names are declared in traefik.yaml. Traefik.yaml wasn't talked about in the write-up because it's implicitly used in the docker-compose.yaml.

**Comment by djdembeck** [comment]
Thanks for the update! I resolved the issue I was having (IP conflict with `ingress` network).

Now I'm seeing an issue where Portainer isn't connecting to the agent environment :thinking: Not sure if that's because you removed the agent section or it's something else.

EDIT: yep, I added this to the compose and portainer works now:
```
  agent:
    image: portainer/agent:latest
    environment:
      # REQUIRED: Should be equal to the service name prefixed by "tasks." when
      # deployed inside an overlay network
      AGENT_CLUSTER_ADDR: tasks.agent
      AGENT_PORT: 9001
      # LOG_LEVEL: debug
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - traefik
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

```
